//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarQubeBootstrapper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BootstrapperResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BootstrapperResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarQubeBootstrapper.Resources.BootstrapperResources", typeof(BootstrapperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Back.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the setup?.
        /// </summary>
        internal static string CancelSetupInformationText {
            get {
                return ResourceManager.GetString("CancelSetupInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to a Microsoft SQL Server Database Instance (Recommended).
        /// </summary>
        internal static string ConfigureDatabaseDialogConnectToSQLLabel {
            get {
                return ResourceManager.GetString("ConfigureDatabaseDialogConnectToSQLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of the following:.
        /// </summary>
        internal static string ConfigureDatabaseDialogDescription {
            get {
                return ResourceManager.GetString("ConfigureDatabaseDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to other Database Instance.
        /// </summary>
        internal static string ConfigureDatabaseDialogOtherDBLabel {
            get {
                return ResourceManager.GetString("ConfigureDatabaseDialogOtherDBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Database that SonarQube Server has to use.
        /// </summary>
        internal static string ConfigureDatabaseDialogSubtitle {
            get {
                return ResourceManager.GetString("ConfigureDatabaseDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Database.
        /// </summary>
        internal static string ConfigureDatabaseDialogTitle {
            get {
                return ResourceManager.GetString("ConfigureDatabaseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogDatabaseNameLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogDatabaseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Password.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogDatabasePasswordLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogDatabasePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Username.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogDatabaseUserLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogDatabaseUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure parameters that need to be set to the new database:.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogDescription {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing new SQL Express instance to use with SonarQube Server..
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogInstallingSQLLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogInstallingSQLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure New Database Instance.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogTitle {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        internal static string ConfigureNewDatabaseInstanceDialogWindowsAuthenticationLabel {
            get {
                return ResourceManager.GetString("ConfigureNewDatabaseInstanceDialogWindowsAuthenticationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogDatabaseNameLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogDatabaseNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL 5.x.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogMySQLLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogMySQLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oracle 10g/11g.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogOracleLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogOracleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Password.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogPasswordLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Port.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogPortLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostgreSQL 8.x/9.x.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogPostgreLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogPostgreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogServerAddressLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogServerAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the Database Type and connection parameters.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogSubtitle {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogTestConnectionButton {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogTestConnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Database Connection.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogTitle {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Username.
        /// </summary>
        internal static string ConfigureOtherDatabaseConnectionDialogUsernameLabel {
            get {
                return ResourceManager.GetString("ConfigureOtherDatabaseConnectionDialogUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube Server requires a TCP port that is not being used by other applications on this machine. The HTTP port is where you will access SonarQube Server through your browser..
        /// </summary>
        internal static string ConfigureTCPPortDialogDescription {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Port Number.
        /// </summary>
        internal static string ConfigureTCPPortDialogHTTPPortLabel {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogHTTPPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure which port SonarQube Server will use.
        /// </summary>
        internal static string ConfigureTCPPortDialogSubtitle {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure TCP Port.
        /// </summary>
        internal static string ConfigureTCPPortDialogTitle {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set custom value for the port.
        /// </summary>
        internal static string ConfigureTCPPortDialogUseCustomLabel {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogUseCustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the default port (9000).
        /// </summary>
        internal static string ConfigureTCPPortDialogUseDefaultLabel {
            get {
                return ResourceManager.GetString("ConfigureTCPPortDialogUseDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string CustomInstallationSummaryDatabaseName {
            get {
                return ResourceManager.GetString("CustomInstallationSummaryDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address.
        /// </summary>
        internal static string CustomInstallationSummaryServerAddress {
            get {
                return ResourceManager.GetString("CustomInstallationSummaryServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Username.
        /// </summary>
        internal static string CustomInstallationSummaryUserName {
            get {
                return ResourceManager.GetString("CustomInstallationSummaryUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A later version of SonarQube is already installed on this machine..
        /// </summary>
        internal static string DowngradeMessage {
            get {
                return ResourceManager.GetString("DowngradeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms in the License Agreement..
        /// </summary>
        internal static string EndUserLicenseAcceptCheckbox {
            get {
                return ResourceManager.GetString("EndUserLicenseAcceptCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read the SonarQube License Agreement.
        /// </summary>
        internal static string EndUserLicenseSubtitle {
            get {
                return ResourceManager.GetString("EndUserLicenseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-User License Agreement.
        /// </summary>
        internal static string EndUserLicenseTitle {
            get {
                return ResourceManager.GetString("EndUserLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at a later time, run Setup Wizard again..
        /// </summary>
        internal static string ExitDialogErrorDescription {
            get {
                return ResourceManager.GetString("ExitDialogErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Weblink: http://localhost:{0}/.
        /// </summary>
        internal static string ExitDialogServiceWebLink {
            get {
                return ResourceManager.GetString("ExitDialogServiceWebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup has been interrupted because of SQL installation failure. Please read log file and perform required steps in order to run the setup successfully..
        /// </summary>
        internal static string ExitDialogSqlFailureDescription {
            get {
                return ResourceManager.GetString("ExitDialogSqlFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the Finish button to exit the Setup Wizard..
        /// </summary>
        internal static string ExitDialogSuccessDescription {
            get {
                return ResourceManager.GetString("ExitDialogSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed the SonarQube Setup Wizard.
        /// </summary>
        internal static string ExitDialogTitle {
            get {
                return ResourceManager.GetString("ExitDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap failed {
            get {
                object obj = ResourceManager.GetObject("failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube 5.2.
        /// </summary>
        internal static string InstallationDialogTitle {
            get {
                return ResourceManager.GetString("InstallationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sonarqubedb.
        /// </summary>
        internal static string InstallationSummaryDatabaseName {
            get {
                return ResourceManager.GetString("InstallationSummaryDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        internal static string InstallationSummaryDatabaseType {
            get {
                return ResourceManager.GetString("InstallationSummaryDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Authentication.
        /// </summary>
        internal static string InstallationSummaryDBAuthentication {
            get {
                return ResourceManager.GetString("InstallationSummaryDBAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string InstallationSummaryDBName {
            get {
                return ResourceManager.GetString("InstallationSummaryDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install SonarQube Server with the following options on this machine.
        /// </summary>
        internal static string InstallationSummaryDescription {
            get {
                return ResourceManager.GetString("InstallationSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string InstallationSummaryDialogDatabaseName {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        internal static string InstallationSummaryDialogDatabaseType {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Username.
        /// </summary>
        internal static string InstallationSummaryDialogDatabaseUsername {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogDatabaseUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install SonarQube Server with the following options on this machine.
        /// </summary>
        internal static string InstallationSummaryDialogDescription {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Location.
        /// </summary>
        internal static string InstallationSummaryDialogInstallationLocationLabel {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogInstallationLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        internal static string InstallationSummaryDialogInstallService {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Port for web access.
        /// </summary>
        internal static string InstallationSummaryDialogPortLabel {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Summary.
        /// </summary>
        internal static string InstallationSummaryDialogTitle {
            get {
                return ResourceManager.GetString("InstallationSummaryDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Port for web access.
        /// </summary>
        internal static string InstallationSummaryHTTPPort {
            get {
                return ResourceManager.GetString("InstallationSummaryHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Location.
        /// </summary>
        internal static string InstallationSummaryInstallLocation {
            get {
                return ResourceManager.GetString("InstallationSummaryInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        internal static string InstallationSummaryInstallService {
            get {
                return ResourceManager.GetString("InstallationSummaryInstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Authentication.
        /// </summary>
        internal static string InstallationSummarySqlAuthentication {
            get {
                return ResourceManager.GetString("InstallationSummarySqlAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSSQL  ({0}).
        /// </summary>
        internal static string InstallationSummarySqlExpressInstance {
            get {
                return ResourceManager.GetString("InstallationSummarySqlExpressInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Summary.
        /// </summary>
        internal static string InstallationSummaryTitle {
            get {
                return ResourceManager.GetString("InstallationSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication.
        /// </summary>
        internal static string InstallationSummaryWindowsAuthentication {
            get {
                return ResourceManager.GetString("InstallationSummaryWindowsAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallButtonText {
            get {
                return ResourceManager.GetString("InstallButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        internal static string InstallDirDatabaseType {
            get {
                return ResourceManager.GetString("InstallDirDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2 Embedded Database (Port {0}).
        /// </summary>
        internal static string InstallDirDatabaseTypeValue {
            get {
                return ResourceManager.GetString("InstallDirDatabaseTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install SonarQube Server with the following options on this machine.
        /// </summary>
        internal static string InstallDirDescription {
            get {
                return ResourceManager.GetString("InstallDirDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Port for web access.
        /// </summary>
        internal static string InstallDirHTTPPort {
            get {
                return ResourceManager.GetString("InstallDirHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the H2 Database option is meant for evaluation only.
        /// </summary>
        internal static string InstallDirInformationEvaluation {
            get {
                return ResourceManager.GetString("InstallDirInformationEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Location.
        /// </summary>
        internal static string InstallDirInstallationLocation {
            get {
                return ResourceManager.GetString("InstallDirInstallationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string InstallDirInstallServiceValue {
            get {
                return ResourceManager.GetString("InstallDirInstallServiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        internal static string InstallDirServiceInstall {
            get {
                return ResourceManager.GetString("InstallDirServiceInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Folder.
        /// </summary>
        internal static string InstallDirTitle {
            get {
                return ResourceManager.GetString("InstallDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string InstallServiceDialogAccountNameLabel {
            get {
                return ResourceManager.GetString("InstallServiceDialogAccountNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        internal static string InstallServiceDialogInstallServiceLabel {
            get {
                return ResourceManager.GetString("InstallServiceDialogInstallServiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string InstallServiceDialogPasswordLabel {
            get {
                return ResourceManager.GetString("InstallServiceDialogPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SonarQube Server as a service on the machine?.
        /// </summary>
        internal static string InstallServiceDialogSubtitle {
            get {
                return ResourceManager.GetString("InstallServiceDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        internal static string InstallServiceDialogTitle {
            get {
                return ResourceManager.GetString("InstallServiceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a system account.
        /// </summary>
        internal static string InstallServiceDialogUseSystemAccount {
            get {
                return ResourceManager.GetString("InstallServiceDialogUseSystemAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a user account.
        /// </summary>
        internal static string InstallServiceDialogUseUserAccount {
            get {
                return ResourceManager.GetString("InstallServiceDialogUseUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.7.
        /// </summary>
        internal static string JavaVersion {
            get {
                return ResourceManager.GetString("JavaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Courier New;}{\f1\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 6.3.9600}\viewkind4\uc1 
        ///\pard\qj\tx959\tx1918\tx2877\tx3836\tx4795\tx5754\tx6713\tx7672\tx8631\b\f0\fs32 The MIT License (MIT)\par
        ///Copyright (c) 2014 Microsoft Corporation\par
        ///\b0\fs20\par
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Softw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account {0} has been granted the Log On As A Service right..
        /// </summary>
        internal static string LogOnAsServiceGrantedMessage {
            get {
                return ResourceManager.GetString("LogOnAsServiceGrantedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account {0} couldn&apos;t be grated the Log On As A Service right..
        /// </summary>
        internal static string LogOnAsServiceNotGrantedMessage {
            get {
                return ResourceManager.GetString("LogOnAsServiceNotGrantedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the operation you wish to perform..
        /// </summary>
        internal static string MaintenanceDialogDescription {
            get {
                return ResourceManager.GetString("MaintenanceDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SonarQube batch file is running on this machine. Please close the batch file instance to proceed with the uninstallation properly..
        /// </summary>
        internal static string MaintenanceDialogSonarBatchRunningError {
            get {
                return ResourceManager.GetString("MaintenanceDialogSonarBatchRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair or remove installation.
        /// </summary>
        internal static string MaintenanceDialogTitle {
            get {
                return ResourceManager.GetString("MaintenanceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string MaintenanceRemoveButtonText {
            get {
                return ResourceManager.GetString("MaintenanceRemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes SonarQube from your computer..
        /// </summary>
        internal static string MaintenanceRemoveDescription {
            get {
                return ResourceManager.GetString("MaintenanceRemoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;epair.
        /// </summary>
        internal static string MaintenanceRepairButtonText {
            get {
                return ResourceManager.GetString("MaintenanceRepairButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairs errors in the most recent installation by fixing missing and corrupt files, shortcuts, and registry entries..
        /// </summary>
        internal static string MaintenanceRepairDescription {
            get {
                return ResourceManager.GetString("MaintenanceRepairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        internal static string PrintButtonText {
            get {
                return ResourceManager.GetString("PrintButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        internal static string ProgressDialogInstallingTitle {
            get {
                return ResourceManager.GetString("ProgressDialogInstallingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0}.
        /// </summary>
        internal static string ProgressDialogInstallProgress {
            get {
                return ResourceManager.GetString("ProgressDialogInstallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairing {0}.
        /// </summary>
        internal static string ProgressDialogRepairProgress {
            get {
                return ResourceManager.GetString("ProgressDialogRepairProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we install SonarQube setup....
        /// </summary>
        internal static string ProgressDialogSubtitle {
            get {
                return ResourceManager.GetString("ProgressDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing SonarQube 5.2.
        /// </summary>
        internal static string ProgressDialogTitle {
            get {
                return ResourceManager.GetString("ProgressDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0}.
        /// </summary>
        internal static string ProgressDialogUninstallingTitle {
            get {
                return ResourceManager.GetString("ProgressDialogUninstallingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0}.
        /// </summary>
        internal static string ProgressDialogUninstallProgress {
            get {
                return ResourceManager.GetString("ProgressDialogUninstallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup has failed in one of the steps....
        /// </summary>
        internal static string ProgressSetupFailedMessage {
            get {
                return ResourceManager.GetString("ProgressSetupFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon setup {
            get {
                object obj = ResourceManager.GetObject("setup", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Disk Space.
        /// </summary>
        internal static string SetupDestinationDialogAvailableDiskSpaceLabel {
            get {
                return ResourceManager.GetString("SetupDestinationDialogAvailableDiskSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string SetupDestinationDialogBrowseButtonText {
            get {
                return ResourceManager.GetString("SetupDestinationDialogBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where you would like to install SonarQube Server 5.2, then click Next.
        /// </summary>
        internal static string SetupDestinationDialogDescription {
            get {
                return ResourceManager.GetString("SetupDestinationDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Disk Space.
        /// </summary>
        internal static string SetupDestinationDialogRequiredDiskSpaceLabel {
            get {
                return ResourceManager.GetString("SetupDestinationDialogRequiredDiskSpaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where should SonarQube Server 5.2 be installed?.
        /// </summary>
        internal static string SetupDestinationDialogSubtitle {
            get {
                return ResourceManager.GetString("SetupDestinationDialogSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination Directory.
        /// </summary>
        internal static string SetupDestinationDialogTitle {
            get {
                return ResourceManager.GetString("SetupDestinationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SonarQube server with MySQL/Oracle/PostgreSQL.
        /// </summary>
        internal static string SetupTypeCustom {
            get {
                return ResourceManager.GetString("SetupTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Installation (Minimal setup for evaluation purposes only).
        /// </summary>
        internal static string SetupTypeEvaluation {
            get {
                return ResourceManager.GetString("SetupTypeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SonarQube server with new or existing SQL Instance.
        /// </summary>
        internal static string SetupTypeExpress {
            get {
                return ResourceManager.GetString("SetupTypeExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose one of the following.
        /// </summary>
        internal static string SetupTypeSelectOption {
            get {
                return ResourceManager.GetString("SetupTypeSelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the appropriate installation option.
        /// </summary>
        internal static string SetupTypeTitle {
            get {
                return ResourceManager.GetString("SetupTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sonarqube_banner {
            get {
                object obj = ResourceManager.GetObject("sonarqube_banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Server Instance for SonarQube Server.
        /// </summary>
        internal static string SqlInstallationDescription {
            get {
                return ResourceManager.GetString("SqlInstallationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this option if you have an existing SQL Server that you would like to use for use with SonarQube Server.
        /// </summary>
        internal static string SqlInstallationExistingSqlDescription {
            get {
                return ResourceManager.GetString("SqlInstallationExistingSqlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an existing SQL Server Instance.
        /// </summary>
        internal static string SqlInstallationExistingSqlOption {
            get {
                return ResourceManager.GetString("SqlInstallationExistingSqlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select this option a new instance of Microsoft SQL Server Express will be installed and configured for use with SonarQube Server.
        /// </summary>
        internal static string SqlInstallationInstallSqlDescription {
            get {
                return ResourceManager.GetString("SqlInstallationInstallSqlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install SQL Server Express.
        /// </summary>
        internal static string SqlInstallationInstallSqlOption {
            get {
                return ResourceManager.GetString("SqlInstallationInstallSqlOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option to install SQL Server Express is disabled because we found an existing instance of SQL Server already on this system..
        /// </summary>
        internal static string SqlInstallationSqlAlreadyInstalled {
            get {
                return ResourceManager.GetString("SqlInstallationSqlAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Server Instance.
        /// </summary>
        internal static string SqlInstallationTitle {
            get {
                return ResourceManager.GetString("SqlInstallationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the SQL instance to be used with the SonarQube Server. Note that the user needs to have at least dbcreator privileges in order to proceed with the installation.
        /// </summary>
        internal static string SqlServerInstanceDescription {
            get {
                return ResourceManager.GetString("SqlServerInstanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed when attempting to access the database instance.
        /// </summary>
        internal static string SqlServerInstanceFailedAuthenticationMessage {
            get {
                return ResourceManager.GetString("SqlServerInstanceFailedAuthenticationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Server Instance.
        /// </summary>
        internal static string SqlServerInstanceNameLabel {
            get {
                return ResourceManager.GetString("SqlServerInstanceNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string SqlServerInstancePasswordLabel {
            get {
                return ResourceManager.GetString("SqlServerInstancePasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Instance to be used with SonarQube Server.
        /// </summary>
        internal static string SqlServerInstanceSubtitle {
            get {
                return ResourceManager.GetString("SqlServerInstanceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SQL Server Instance.
        /// </summary>
        internal static string SqlServerInstanceTitle {
            get {
                return ResourceManager.GetString("SqlServerInstanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string SqlServerInstanceUserNameLabel {
            get {
                return ResourceManager.GetString("SqlServerInstanceUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Logged in users as authentication (or specify alternate credentials below).
        /// </summary>
        internal static string SqlServerInstanceWindowsCredentialsLabel {
            get {
                return ResourceManager.GetString("SqlServerInstanceWindowsCredentialsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select current Windows credentials or SQL authentication to setup SonarQube server..
        /// </summary>
        internal static string SqlServerNewUserCredentialsDescription {
            get {
                return ResourceManager.GetString("SqlServerNewUserCredentialsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the authentication method for new SQL express.
        /// </summary>
        internal static string SqlServerNewUserCredentialsTitle {
            get {
                return ResourceManager.GetString("SqlServerNewUserCredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap succeeded {
            get {
                object obj = ResourceManager.GetObject("succeeded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to Continue, or Cancel to exit the Setup..
        /// </summary>
        internal static string WelcomeDialogAction {
            get {
                return ResourceManager.GetString("WelcomeDialogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will install SonarQube Server 5.2 on your computer. The wizard will lead you step by step through the installation..
        /// </summary>
        internal static string WelcomeDialogDescription {
            get {
                return ResourceManager.GetString("WelcomeDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java SE Runtime Engine v7 or up is required for SonarQube server, please install the same from this link and restart installation.
        /// </summary>
        internal static string WelcomeDialogJavaVersionError {
            get {
                return ResourceManager.GetString("WelcomeDialogJavaVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other version of SonarQube service or process is installed on this machine already. Please note this setup doesn&apos;t upgrade/downgrade the older SonarQube installation..
        /// </summary>
        internal static string WelcomeDialogSonarQubeRunningWarning {
            get {
                return ResourceManager.GetString("WelcomeDialogSonarQubeRunningWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the SonarQube Server 5.2 Installation Wizard.
        /// </summary>
        internal static string WelcomeDialogTitle {
            get {
                return ResourceManager.GetString("WelcomeDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string WelcomeDialogTryAgain {
            get {
                return ResourceManager.GetString("WelcomeDialogTryAgain", resourceCulture);
            }
        }
    }
}
